### ISSUE TITLE
Categories page not rendered if no categories used in posts

### ISSUE THREAD

**Issue by devurandom** [Keats/even#7]
When no categories are being used in any post, the `/categories` page will not be rendered.

**Comment by Keats** [comment]
That's intended, taxonomies pages in gutenberg are only rendered if there is at least one item

**Comment by Keats** [comment]
It is a gutenberg issue but it is the intented behaviour so it is unlikely to be changed.

**Comment by devurandom** [comment]
I would expect all taxonomies I configure in `config.toml` to also be generated during build, independently of it being in active use -- "I said I want this taxonomy, so give it to me". I'm generally in favour of more predictable behaviour.

**Comment by Keats** [comment]
That's a fair point, we can discuss it in the Gutenberg repo
